[package]
name = "stakevue_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
odra = { version = "2.4.0", default-features = false }
odra-modules = { version = "2.4.0", default-features = false }
odra-cli = { version = "2.4.0", optional = true }
odra-casper-livenet-env = { version = "2.4.0", optional = true }

[dev-dependencies]
odra-test = { version = "2.4.0", default-features = false }

[build-dependencies]
odra-build = { version = "2.4.0", default-features = false }

[features]
default = []
livenet = ["odra-cli", "odra-casper-livenet-env"]

[[bin]]
name = "stakevue_contract_build_contract"
path = "bin/build_contract.rs"
test = false

[[bin]]
name = "stakevue_cli"
path = "bin/cli.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "configure_v9"
path = "bin/configure_v9.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "deploy_v10"
path = "bin/deploy_v10.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "test_stake_v9"
path = "bin/test_stake_v9.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "configure_v10"
path = "bin/configure_v10.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "test_stake_v10"
path = "bin/test_stake_v10.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "test_stake_simple"
path = "bin/test_stake_simple.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "deploy_v11"
path = "bin/deploy_v11.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "test_stake_v82"
path = "bin/test_stake_v82.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "deploy_v12"
path = "bin/deploy_v12.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "test_stake_v12"
path = "bin/test_stake_v12.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "deploy_v13"
path = "bin/deploy_v13.rs"
required-features = ["livenet"]
test = false

[[bin]]
name = "test_stake_v13"
path = "bin/test_stake_v13.rs"
required-features = ["livenet"]
test = false
