[package]
name = "stakevue-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
casper-contract = "2.0.0"
casper-types = "2.0.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
